server:
  port: 9080
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
      idle-timeout: 30
  jms:
    pub-sub-domain: true #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置pub-sub-domain为true